services:
  sql_db:
    image: mysql
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    ports:
      - '3307:3306'
    volumes:
      - ./data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=books

  api:
    build: ./api
    container_name: api_c
    ports:
      - '4000:4000'
    depends_on:
      - sql_db
    volumes:
      - ./api:/app
      - /api/node_modules
    environment:
      - DATABASE_HOST=sql_db
    tty: true
    stdin_open: true
